services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=the-network
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@dev.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - "80:80"
volumes:
  db:
